Commit mentorat
acecconato/AnthonyCecconato_5_18102021 pull request #39
Opened 2022-02-16 12:06 UTC by acecconato

2022-02-16 12:16 UTC, TBoileau requested changes

2022-02-16 12:16 UTC, TBoileau commented on src/Database/Adapter/MySQLAdapterInterface.php
> +     */
Pourquoi ces méthodes sont ici et pas dans AdapterInterface, pas sur que cette interface soit utile d'ailleurs.
On ne devrait avoir qu'une seule interface et X implémntations si besoin

2022-02-16 12:16 UTC, TBoileau commented on src/Database/DataMapper.php
> +    }
Hum ça sert à quoi ? Car un mapper, ne sert qu'à récupérer le mapping d'une entité en mode flat, en gros juste un moyen de récupérer ses infos
La j'ai l'impression que tu veux hydrater quelques chose

2022-02-16 12:16 UTC, TBoileau commented on src/Entity/EntityInterface.php
> +interface EntityInterface
A quoi te sert cette interface ?

2022-02-16 12:16 UTC, TBoileau commented on src/Entity/Post.php
> +class Post extends EntityManager implements EntityInterface
Heu pourquoi une entité étant un EntityManager, l'entity manager est un service

2022-02-16 12:16 UTC, TBoileau commented on src/Entity/Post.php
> +class Post extends EntityManager implements EntityInterface
Une entité ne devrait étendre rien, si ce n'est une autre entité, et il ne devrait pas non plus avoir d'interface

2022-02-16 12:16 UTC, TBoileau commented on src/Repository/Repository.php
> +    }
Ce n'est pas responsabilité du repository de générer un Uuid

2022-02-16 12:16 UTC, TBoileau commented on src/Repository/Repository.php
> +    }
Il ne devrait pas avoir d'adapter. On injecte seulement l'entité manager à l'intérieur

2022-02-17 10:21 UTC, acecconato commented on src/Repository/Repository.php
> +    }
Ce n'est pas l'entitymanager qui est censé appeler le repository ?

2022-02-17 10:22 UTC, acecconato commented on src/Repository/Repository.php
> +    }
C'est quoi c'est un service à part ou peut être l'entity manager ?

2022-02-17 10:23 UTC, acecconato commented on src/Entity/Post.php
> +class Post extends EntityManager implements EntityInterface
Oui pour l'EM c'est moche, mais pour l'EntityInterface je me dis que c'est surtout pour pouvoir typer mes méthodes de mon Entity Manager, par exemple $em->persist(EntityInterface $entity), sinon comment faire pour s'assurer que l'on attends bien une entité sans classe parente ou interface, selon l'entité que l'on lui passe ? (User, Post..)

2022-02-17 10:24 UTC, acecconato commented on src/Database/Adapter/MySQLAdapterInterface.php
> +     */
J'ai remonté ces méthodes dans l'AdapterInterface et supprimé le MySQLInterface, j'ai mis un return mixed sur le connect, j'ai juste un doute pour la méthode query() car elle prends en paramètre un string $rawquery et une array $bind pour faire des requêtes préparés mais ca a l'air très spécifique au SQL ce genre de chose non ? Si je souhaite un jour mettre autre chose est ce que le bind sera toujours pertinent ?

2022-02-17 10:27 UTC, TBoileau commented on src/Repository/Repository.php
> +    }
Non du tout, le repository est un service à laquelle tu injectes l'entity manager

2022-02-17 10:28 UTC, TBoileau commented on src/Repository/Repository.php
> +    }
ça peut être un service à part ou simplement utilisé de manière native

2022-02-17 10:28 UTC, TBoileau commented on src/Entity/Post.php
> +class Post extends EntityManager implements EntityInterface
Parce que tu vas vérifier avec le data mapper si c'est bien une entité

2022-02-17 10:29 UTC, TBoileau commented on src/Database/Adapter/MySQLAdapterInterface.php
> +     */
Non mais dans TOUS les cas tu gères avec PDO. Ce qui va changer c'est juste l'url de connexion que tu gères déjà dans MysqlAdapter

2022-02-21 18:21 UTC, TBoileau requested changes

2022-02-21 18:21 UTC, TBoileau commented on src/Database/DataMapper.php
> +    public function mapEntity(object $entity): array
Remplacer par un string (qui sera composer du FQCN)

2022-02-21 18:21 UTC, TBoileau commented on src/Database/DataMapper.php
> +        ];
Stocker le mapping quelque part, et ainsi éviter de refaire à chaque fois le même traitement, alors que tu aurais supposément déjà fait un mapping de cette même entité

2022-02-21 18:21 UTC, TBoileau commented on src/Entity/EntityManager.php
> +    }
Pourquoi avoir besoin d’assesseurs pour l'adapter alors que tu as un getConnection` plus bas? Je pense que c'est inutile.

2022-02-21 18:21 UTC, TBoileau commented on src/Entity/Post.php
> +     */
La PHPDoc est inutile si tu utilises le typage

2022-02-21 18:21 UTC, TBoileau commented on src/ORM/UnitOfWork.php
> +    }
Inutile

2022-02-21 18:21 UTC, TBoileau commented on src/ORM/UnitOfWork.php
> +    }
Cette méthode va exécuter les requêtes (insertions  modifications, suppression).
Pas besoin d'argument

2022-03-07 18:15 UTC, TBoileau requested changes

2022-03-07 18:15 UTC, TBoileau commented on src/Attribute/Column.php
> +        private string $type = 'string',
Utiliser enum

2022-03-07 18:15 UTC, TBoileau commented on src/Attribute/Column.php
> +        private bool $unique = false
Mettre en publique

2022-03-07 18:15 UTC, TBoileau commented on src/Attribute/Entity.php
> +        protected string $repositoryClass
Pourquoi protected ? => publique

2022-03-07 18:15 UTC, TBoileau commented on src/Attribute/Table.php
> +        private string $tableName
Mettre en public

2022-03-07 18:15 UTC, TBoileau commented on src/Database/DataMapper.php
> +        return $this->entities->offsetGet($entity);
Tu te compliques la viee, tu peux directement recupérer un instance de tes classe de mapping : https://www.php.net/manual/fr/reflectionattribute.newinstance.php

2022-03-07 18:15 UTC, TBoileau commented on src/Database/MapperInterface.php
> +    public function mapEntity(string $entity): array;
Je l'appelerais "resolve"

2022-03-07 18:15 UTC, TBoileau commented on src/ORM/Persister/EntityPersister.php
> +}
Useless

2022-03-07 18:15 UTC, TBoileau commented on src/Database/DataMapper.php
> +        return $this->entities->offsetGet($entity);
Au lieu de renvoyer un tableau avec les instance de ton mapping, implémenter une classe Metadata, qui comprend :

- class => FQCN
- entity
- table
- id
- columns

2022-03-14 18:08 UTC, TBoileau requested changes

2022-03-14 18:08 UTC, TBoileau commented on src/Database/Adapter/MySQLAdapter.php
> +                $bind = $transaction[1];
Pas très fan de ça, soit créer une classe simple ou utiliser un tableau associatif :
```php
/**
 * @var array<array-key, array{query: string, bind: array}>
 */
private array $transactions = [];

```

2022-03-14 18:08 UTC, TBoileau commented on src/Database/DataMapper.php
> +                    throw new Exception('Unhandled attribute ' . $attribute->getName());
Je ne ferais pas de boucle, utiliser le première paramètre de getAttributes

2022-03-14 18:08 UTC, TBoileau commented on src/ORM/UnitOfWork.php
> +                    Type::HTML => htmlspecialchars($object->{'get' . ucfirst($column->propertyName)}()),
ne jamais faire ça en entrée, l'échappement du html se fait toujours à l'affichage

2022-03-17 13:04 UTC, acecconato commented on src/Database/DataMapper.php
> +                    throw new Exception('Unhandled attribute ' . $attribute->getName());
J'aimerai le laisser car ça me permet de voir s'il y a un attribut non prévu facilement et il faut  quand même créer les instances, ça reste c'est assez verbeux : 

```php
$tableAttributeInstance = ($reflClass->getAttributes(Table::class))->newInstance();
$metadatas->setTable($reflClass->getAttributes(Table::class));
```

Qu'est ce que tu en pense ?

2022-03-28 17:09 UTC, TBoileau requested changes

2022-03-28 17:09 UTC, TBoileau commented on src/Entity/AbstractEntity.php
> +}
Pas fan de cette classe abstraite

2022-03-28 17:09 UTC, TBoileau commented on src/ORM/Hydration/AbstractHydrator.php
> +}
Inutile

2022-04-04 17:13 UTC, TBoileau approved these changes

2022-04-04 17:22 UTC, acecconato commented
close #8 
close #9

2022-04-04 17:22 UTC, merged